### ISSUE TITLE
does it support I420

### ISSUE THREAD

**Issue by radioman** [stunpix/yuvit#13]
i've tested all combinations and can't get yuv file to play corectly, i see green screen lines instead, somehow it encodes jpg differently than jpeg2yuv, or i'm missing something?

**Comment by stunpix** [comment]
I completely missed your message, because github for some reason didn't send me any notifications on it.

If answer is still actual: yes, tool does support I420. The I420 is planar format with Y plane followed by U and V planes subsampled by 2 vertically and horizontally. To convert images to I420 you need run tool as following:

    any2yuv -s h2v2 image.jpg

If an output image will have broken colors, try add `-r` (reverse chroma) option.

**Comment by mannyglover** [comment]
It would be pretty handy if in your ready, you had a table that translated the commands to the output type (e.g., "-s h2v2" == I420").  Thanks, Manny.

**Comment by stunpix** [comment]
Yep, sounds reasonable. I'll update it.
